# Rime default settings
# encoding: utf-8

config_version: "0.37"

schema_list:
  - schema: wubi
  - schema: pinyin

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - extended_charset
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  page_size: 8

punctuator:
  import_preset: symbols

key_binder:
  bindings:

recognizer:
  patterns:
    punct: "^/[a-z]+$"
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Shift_L: noop
    Shift_R: noop
    Control_L: noop
    Control_R: noop
    Caps_Lock: clear
    Eisu_toggle: clear
